### ISSUE TITLE
Short-term TODO

### ISSUE THREAD

**Issue by catb0t** [exercism/xfactor#19]
- [ ] Pick the next 8 exercises and make sure they're doable, and cover one entirely new skill or topic at a time.
- [ ] Implement the mentioned exercises.
- [ ] Update config.json with the new exercises.
- [ ] Update https://github.com/catb0t/exercism.factor to verify new config.json format.

**Comment by hiljusti** [comment]
Hey @catb0t I'm curious if you're still active, and if so, whether you're still interested in contributing to Exercism. It's fine if you've moved on, either way will help me understand whether or not to point people at exercism.factor

I've been taking a much more manual approach so far, which has let me (locally) use just `tools.test` and avoid some pitfalls of vocabulary naming. I'm just using some spare time but I'm going to get close to a launchable track soon (maybe in a few weeks or a month or so)

**Comment by keiravillekode** [comment]
@booniepepper  We now use a generator for practice exercise tests.
